SELECT *
 from ANIMAL_INS
 order by ANIMAL_ID;
 
SELECT NAME, DATETIME
 from ANIMAL_INS
 order by ANIMAL_ID desc;
 
SELECT ANIMAL_ID, NAME
 from ANIMAL_INS
 where INTAKE_CONDITION='Sick'
 order by ANIMAL_ID;
 
SELECT ANIMAL_ID, NAME
 from ANIMAL_INS
 where INTAKE_CONDITION != 'Aged'
 order by ANIMAL_ID;
 
SELECT ANIMAL_ID, NAME
 from ANIMAL_INS
 where INTAKE_CONDITION='Sick'
 order by ANIMAL_ID;

SELECT ANIMAL_ID, NAME, DATETIME
 from ANIMAL_INS
 order by NAME, DATETIME desc;

SELECT NAME
 from (SELECT * 
        FROM ANIMAL_INS
        order by DATETIME)
 WHERE ROWNUM < 2;
 
SELECT max(datetime)
 from animal_ins;
 
SELECT min(datetime)
 from animal_ins;

SELECT count(*)
 from animal_ins;
 
SELECT count(distinct name)
 from animal_ins
 where name is not null;
 
SELECT ANIMAL_TYPE, count(*)
 from animal_ins
 group by ANIMAL_TYPE
 order by ANIMAL_TYPE;
 
SELECT NAME, COUNT(NAME)
 FROM ANIMAL_INS
 WHERE NAME IS NOT NULL
 GROUP BY NAME
 HAVING COUNT(NAME)>=2
 ORDER BY NAME;
 
SELECT NAME, COUNT(NAME)
 FROM ANIMAL_INS
 WHERE NAME IS NOT NULL
 GROUP BY NAME
 HAVING COUNT(NAME)>=2
 ORDER BY NAME;
 
SELECT A.HOUR, COUNT(D.DATETIME)
 FROM (SELECT LEVEL-1 AS HOUR
        FROM DUAL
        CONNECT BY LEVEL < 25) A
 LEFT JOIN ANIMAL_OUTS D ON A.HOUR = TO_NUMBER(TO_CHAR(D.DATETIME,'HH24'))
 GROUP BY A.HOUR
 ORDER BY A.HOUR;
 
SELECT ANIMAL_ID
 FROM ANIMAL_INS
 WHERE NAME IS NULL
 ORDER BY ANIMAL_ID;
 
SELECT ANIMAL_ID
 FROM ANIMAL_INS
 WHERE NAME IS NOT NULL
 ORDER BY ANIMAL_ID;
 
SELECT ANIMAL_TYPE, NVL(NAME,'No name'), SEX_UPON_INTAKE
 FROM ANIMAL_INS
 ORDER BY ANIMAL_ID;
 
SELECT ANIMAL_ID, NAME
 FROM ANIMAL_OUTS
MINUS
SELECT ANIMAL_ID, NAME
 FROM ANIMAL_INS
 ORDER BY ANIMAL_ID;
 
SELECT A.ANIMAL_ID, A.NAME
 FROM ANIMAL_INS A, ANIMAL_OUTS B
 WHERE A.ANIMAL_ID=B.ANIMAL_ID AND A.DATETIME > B.DATETIME
 ORDER BY A.DATETIME;
 
SELECT *
 FROM (SELECT A.NAME, A.DATETIME
        FROM ANIMAL_INS A LEFT JOIN ANIMAL_OUTS B ON A.ANIMAL_ID =B.ANIMAL_ID
        WHERE B.ANIMAL_ID IS NULL
        ORDER BY A.DATETIME)
 WHERE ROWNUM < 4;
 
SELECT *
 FROM (SELECT A.NAME, A.DATETIME
        FROM ANIMAL_INS A LEFT JOIN ANIMAL_OUTS B ON A.ANIMAL_ID =B.ANIMAL_ID
        WHERE B.ANIMAL_ID IS NULL
        ORDER BY A.DATETIME)
 WHERE ROWNUM < 4;
 
SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE
 FROM ANIMAL_INS
 WHERE NAME IN ('Lucy','Ella','Pickle','Rogan','Sabrina','Mitty')
 ORDER BY ANIMAL_ID;
 
SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE
 FROM ANIMAL_INS
 WHERE NAME IN ('Lucy','Ella','Pickle','Rogan','Sabrina','Mitty')
 ORDER BY ANIMAL_ID;
 
SELECT ANIMAL_ID, NAME, 
       CASE WHEN SEX_UPON_INTAKE LIKE 'Intact%' THEN 'X'
       ELSE 'O' END Áß¼ºÈ­
 FROM ANIMAL_INS
 ORDER BY ANIMAL_ID;
 
SELECT *
 FROM (SELECT A.ANIMAL_ID, A.NAME
        FROM ANIMAL_INS A, ANIMAL_OUTS B
        WHERE A.ANIMAL_ID=B.ANIMAL_ID 
        ORDER BY B.DATETIME-A.DATETIME DESC)
 WHERE ROWNUM < 3;
 
SELECT ANIMAL_ID, NAME, TO_CHAR(DATETIME,'YYYY-MM-DD')
 FROM ANIMAL_INS
 ORDER BY ANIMAL_ID;